apiVersion: v1
kind: Service
metadata:
  name: udash-urtmp-service
  namespace: udash-urtmp
spec:
  type: NodePort
  selector:
    app: udash-urtmp
  ports:
    - name: udash
      port: 5858
      targetPort: 5858
      nodePort: 30200
    - name: urtmp
      port: 11945
      targetPort: 11945
      nodePort: 30300
